### PR TITLE
Added Webmaster Tools verification file

### PR DESCRIPTION
**Pull request by samdutton**
See [Webmaster Tools page](https://www.google.com/webmasters/verification/verification?hl=en&siteUrl=http://apprtc.appspot.com/&theme=wmt&continue=https://www.google.com/webmasters/tools/dashboard?hl%3Den%26siteUrl%3Dhttp://apprtc.appspot.com/%26sig%3DALjLGbN1gpKD5olQsq2h-kY4YoSGg2MVNw).

### CODE REVIEW

**Comment by samdutton** [comment]
@juberti @marwahvikas this file will need to be deployed (we can get rid of it later, if we want).

**Comment by juberti** [comment]
lgtm

**Comment by samdutton** [comment]
Test file still needs to be deployed: [apprtc.appspot.com/google1b7eb21c5b594ba0.html](https://apprtc.appspot.com/google1b7eb21c5b594ba0.html).

This is order for us to be able to test robots.txt functionality.

@juberti @chuckhays @marwahvikas

**Comment by marwahvikas** [comment]
okay Sam let me try deploy apprtc.

**Comment by juberti** [comment]
I think the issue is that we need to put this in the /html subdir, so that it is served as a static file.

**Comment by juberti** [comment]
or add a app.yaml directive to serve this as a static file.

**Comment by marwahvikas** [comment]
Thanks Justin, checked with @jiayliu , she said it should be there in the /html subdir. So just need a push. Will double check on my side.

**Comment by jiayliu** [comment]
It actually needs https://github.com/webrtc/apprtc/pull/43 to be able to verify. Please wait for the PR to land before pushing.

**Comment by marwahvikas** [comment]
cool thanks Jiayang!

**Pull request merged**
