### PR TITLE
Rename register to join and bye to leave for GAE API

### PR DESCRIPTION
**Pull request by jiayliu**
I did't keep the old API since this branch will not be pushed to prod apprtc, so no compatibility issue.

### CODE REVIEW

**Comment by jiayliu** [comment]
@tkchin @chuckhays @juberti PTAL

**Comment by juberti** [comment]
I think we should maintain backcompat to ensure that both old and new clients can work with prod or the development server.

**Comment by jiayliu** [comment]
Fine. Added back.

**Comment by juberti** [comment]
lgtm. Let's merge this commit to trunk as well.

**Comment by chuckhays** [comment]
lgtm as well.

**Pull request merged**
