### PR TITLE
Add Google API dependencies.

### PR DESCRIPTION
**Pull request by milkypostman**
@jiayliu 

This is gathered from [google-api-python-client](https://code.google.com/p/google-api-python-client/downloads/list) and is the `google-api-python-client-gae-1.2.zip` unzipped so that our API can use it.

### CODE REVIEW

**Comment by jiayliu** [comment]
lgtm

**Comment by juberti** [comment]
Since these files aren't under the top-level LICENSE, I think they should go under an apprtc/third_party directory.

**Comment by milkypostman** [comment]
@juberti should I add a LICENSE file or README inside the `third_party` directory mentioning something about licensing?

**Comment by juberti** [comment]
Yeah, I think a README explaining that this is third-party code (and why we need it here, as opposed to pulling it as a npm module) is an excellent idea.

**Comment by milkypostman** [comment]
readme added. ptal

**Pull request merged**
